### ISSUE TITLE
Assign difficulty to each course

### ISSUE THREAD

**Issue by andreilgeorgescu** [riverwalk-software/astro-test#57]

**Comment by daniel-ciocirlan** [comment]
Here's a course difficulty list, with the tags "easy", "intermediate", "advanced", in the format `$link - $difficulty`.

https://rockthejvm.com/p/scala-at-light-speed - easy
https://rockthejvm.com/p/scala - intermediate
https://rockthejvm.com/p/advanced-scala - advanced
https://rockthejvm.com/p/scala-functional-programming-interview-practice - intermediate
https://rockthejvm.com/p/kotlin-at-light-speed - easy
https://rockthejvm.com/p/kotlin-essentials - intermediate
https://rockthejvm.com/p/advanced-kotlin - advanced
https://rockthejvm.com/p/kotlin-coroutines - intermediate
https://rockthejvm.com/p/zio - intermediate
https://rockthejvm.com/p/zio-rite-of-passage - advanced
https://rockthejvm.com/p/cats-effect - advanced
https://rockthejvm.com/p/cats - advanced
https://rockthejvm.com/p/typelevel-rite-of-passage - advanced
https://rockthejvm.com/p/flink - intermediate
https://rockthejvm.com/p/spark-essentials - easy
https://rockthejvm.com/p/spark-streaming - intermediate
https://rockthejvm.com/p/spark-optimization - intermediate
https://rockthejvm.com/p/spark-performance-tuning - intermediate
https://rockthejvm.com/p/akka-essentials - intermediate
https://rockthejvm.com/p/akka-streams - advanced
https://rockthejvm.com/p/akka-http - intermediate

**Comment by andreilgeorgescu** [comment]
What are the difficulties of the following courses?
 
- [Akka Classic Persistence](https://rockthejvm.com/p/akka-persistence)
- [Akka Classic Remoting and Clustering](https://rockthejvm.com/p/akka-remoting-clustering)
- [Akka Classic Serialization](https://rockthejvm.com/p/akka-serialization)

**Comment by daniel-ciocirlan** [comment]
I could have sworn I've commented here. Here's the difficulty for each course:

- Akka Classic Persistence - intermediate
- Akka Classic Remoting/Clustering - advanced
- Akka Classic Serialization - easy
