### ISSUE TITLE
Create a design theme

### ISSUE THREAD

**Issue by andreilgeorgescu** [riverwalk-software/astro-test#69]

**Comment by daniel-ciocirlan** [comment]
I've spent a few hours today trying to experiment with colors and color palettes, and I found out just how little I know about colors and anything design.

I browsed through (palettes on Coolors)[https://coolors.co/palettes/popular]

maybe you can find a color palette to use on the main components e.g. backdrops, cards, links, etc:

- a dark color palette - I'm thinking of something like this one?
- a light color palette - I'd like something a bit more lively than just white, but seems a bit more difficult to find (too childish, too bright, too Romanian-flag, etc)

**Comment by andreilgeorgescu** [comment]
- [ ] pick color palette for
  - [ ] page backdrop
  - [ ] articles/videos/course cards
  - [ ] article tags
  - [ ] text
  - [ ] links
  - [ ] buttons
  - [ ] CTA button
  - [ ] curriculum sections
- [ ] dark color palette: https://coolors.co/palette/001021-001625-011c2a-01222e-012832-022f37-02353b-023b3f-034144-034748
- [ ] light color palette: TODO
