### ISSUE TITLE
Upload Typelevel Rite of Passage demonstration video to YouTube as unlisted

### ISSUE THREAD

**Issue by daniel-ciocirlan** [riverwalk-software/astro-test#88]
[This video](https://rtjvm-website-blog-images.s3.eu-west-1.amazonaws.com/speedrun.mp4) which is the video from the yellow section of the [Typelevel Rite of Passage course](https://rockthejvm.com/p/typelevel-rite-of-passage) is an MP4 file that is acting as a longform animation. MP4 is too large for SEO performance and doesn't work with our layout so I converted it to WebP but that actually made it larger and it takes too long to load. Also the large size is taking up too much space in Git LFS.

If you can upload this as an unlisted YouTube video, then I can just embed it on the course page for the best of both worlds. I've seen other course pages do a similar thing.

**Comment by andreilgeorgescu** [comment]
Thank you, but I was referring to the animation in the yellow section. The video you uploaded is the same as [this public one](https://www.youtube.com/watch?v=gIcHeE5z7Oc) right?

**Comment by daniel-ciocirlan** [comment]
Uploaded directly:

https://github.com/user-attachments/assets/714597f9-9ad1-4de1-bdc7-367d46fe22c8

**Comment by daniel-ciocirlan** [comment]
Also on YouTube:

https://youtu.be/D83MaZYUsik
